version: "3"

services:
  drogon:
    # test用のイメージ
    # 本番用に体裁を整えて作る必要あり
    image: sotta/kousen_basic_research:latest
    container_name: kousen
    logging:
      driver: json-file
    tty: true
    # ポートの設定
    # なんかデフォルトは5555やった。いみふ5555は多分使わん
    ports:
      - "8085:80"
    # コンテナ内のディレクトリとマウント
    # 試験的にhome直下にプロジェクト作成
    volumes:
      - .:/home/work

  postgres:
    container_name: db
    hostname: ${POSTGRES_HOSTNAME}
    build: ./kousen/postgres/
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./kousen/postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}

volumes:
  db: