version: "3"

services:
  drogon:
    # test用のイメージ
    # 本番用に体裁を整えて作る必要あり
    image: sotta/kousen_basic_research:latest
    container_name: kousen
    logging:
      driver: json-file
    tty: true
    # ポートの設定
    # なんかデフォルトは5555やった。いみふ5555は多分使わん
    ports:
      - "8085:80"
    # コンテナ内から"host.docker.internal"でホストのlocalhostに接続
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # コンテナ内のディレクトリとマウント
    # 試験的にhome直下にプロジェクト作成
    volumes:
      - .:/home/work

  postgres:
    container_name: db
    hostname: ${POSTGRES_HOSTNAME}
    build: ./kousen/postgres/
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./kousen/postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - 8088:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGAD_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGAD_PASS}
    depends_on:
      - postgres


volumes:
  db:
  pgadmin: